/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'isPublished' : boolean,
  'createdAt' : Time,
  'description' : string,
  'instructorId' : Principal,
  'category' : string,
  'price' : bigint,
}
export interface Enrollment {
  'id' : bigint,
  'studentId' : Principal,
  'enrolledAt' : Time,
  'courseId' : bigint,
}
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'order' : bigint,
  'sectionId' : bigint,
  'videoUrl' : string,
  'courseId' : bigint,
}
export interface LessonProgress {
  'lessonId' : bigint,
  'completedAt' : Time,
  'studentId' : Principal,
  'courseId' : bigint,
}
export interface Section {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'courseId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLesson' : ActorMethod<
    [bigint, bigint, string, string, bigint, bigint],
    Lesson
  >,
  'addSection' : ActorMethod<[bigint, string, bigint], Section>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, string, bigint, string],
    Course
  >,
  'deleteCourse' : ActorMethod<[bigint], boolean>,
  'deleteLesson' : ActorMethod<[bigint], boolean>,
  'deleteSection' : ActorMethod<[bigint], boolean>,
  'enrollCourse' : ActorMethod<[bigint], Enrollment>,
  'getAdminCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getAllStudents' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getCourseCurriculum' : ActorMethod<
    [bigint],
    Array<[Section, Array<Lesson>]>
  >,
  'getCourseProgress' : ActorMethod<
    [bigint],
    {
      'totalLessons' : bigint,
      'completedLessons' : bigint,
      'percentage' : bigint,
    }
  >,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getMyEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getMyProgress' : ActorMethod<
    [],
    Array<{ 'courseId' : bigint, 'percentage' : bigint }>
  >,
  'getStats' : ActorMethod<
    [],
    {
      'totalEnrollments' : bigint,
      'totalStudents' : bigint,
      'totalCourses' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEnrolled' : ActorMethod<[bigint], boolean>,
  'markLessonComplete' : ActorMethod<[bigint, bigint], LessonProgress>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCourse' : ActorMethod<
    [bigint, string, string, string, bigint, string, boolean],
    Course
  >,
  'updateLesson' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    Lesson
  >,
  'updateSection' : ActorMethod<[bigint, string, bigint], Section>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];