/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'order' : IDL.Nat,
  'sectionId' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const Section = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Time,
  'description' : IDL.Text,
  'instructorId' : IDL.Principal,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Enrollment = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Principal,
  'enrolledAt' : Time,
  'courseId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const LessonProgress = IDL.Record({
  'lessonId' : IDL.Nat,
  'completedAt' : Time,
  'studentId' : IDL.Principal,
  'courseId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLesson' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [Lesson],
      [],
    ),
  'addSection' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Section], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Course],
      [],
    ),
  'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'enrollCourse' : IDL.Func([IDL.Nat], [Enrollment], []),
  'getAdminCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourseCurriculum' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(Section, IDL.Vec(Lesson)))],
      ['query'],
    ),
  'getCourseProgress' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'totalLessons' : IDL.Nat,
          'completedLessons' : IDL.Nat,
          'percentage' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getMyProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'courseId' : IDL.Nat, 'percentage' : IDL.Nat }))],
      ['query'],
    ),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEnrollments' : IDL.Nat,
          'totalStudents' : IDL.Nat,
          'totalCourses' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEnrolled' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'markLessonComplete' : IDL.Func([IDL.Nat, IDL.Nat], [LessonProgress], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCourse' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [Course],
      [],
    ),
  'updateLesson' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [Lesson],
      [],
    ),
  'updateSection' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Section], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'order' : IDL.Nat,
    'sectionId' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const Section = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Time,
    'description' : IDL.Text,
    'instructorId' : IDL.Principal,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Enrollment = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Principal,
    'enrolledAt' : Time,
    'courseId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const LessonProgress = IDL.Record({
    'lessonId' : IDL.Nat,
    'completedAt' : Time,
    'studentId' : IDL.Principal,
    'courseId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLesson' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [Lesson],
        [],
      ),
    'addSection' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Section], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Course],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'enrollCourse' : IDL.Func([IDL.Nat], [Enrollment], []),
    'getAdminCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourseCurriculum' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(Section, IDL.Vec(Lesson)))],
        ['query'],
      ),
    'getCourseProgress' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'totalLessons' : IDL.Nat,
            'completedLessons' : IDL.Nat,
            'percentage' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getMyProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'courseId' : IDL.Nat, 'percentage' : IDL.Nat }))],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEnrollments' : IDL.Nat,
            'totalStudents' : IDL.Nat,
            'totalCourses' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEnrolled' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'markLessonComplete' : IDL.Func([IDL.Nat, IDL.Nat], [LessonProgress], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCourse' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [Course],
        [],
      ),
    'updateLesson' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [Lesson],
        [],
      ),
    'updateSection' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Section], []),
  });
};

export const init = ({ IDL }) => { return []; };