/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Lesson {
    id: bigint;
    title: string;
    duration: bigint;
    order: bigint;
    sectionId: bigint;
    videoUrl: string;
    courseId: bigint;
}
export interface Enrollment {
    id: bigint;
    studentId: Principal;
    enrolledAt: Time;
    courseId: bigint;
}
export interface Section {
    id: bigint;
    title: string;
    order: bigint;
    courseId: bigint;
}
export interface LessonProgress {
    lessonId: bigint;
    completedAt: Time;
    studentId: Principal;
    courseId: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface Course {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    isPublished: boolean;
    createdAt: Time;
    description: string;
    instructorId: Principal;
    category: string;
    price: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLesson(sectionId: bigint, courseId: bigint, title: string, videoUrl: string, duration: bigint, order: bigint): Promise<Lesson>;
    addSection(courseId: bigint, title: string, order: bigint): Promise<Section>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCourse(title: string, description: string, category: string, price: bigint, thumbnailUrl: string): Promise<Course>;
    deleteCourse(id: bigint): Promise<boolean>;
    deleteLesson(id: bigint): Promise<boolean>;
    deleteSection(id: bigint): Promise<boolean>;
    enrollCourse(courseId: bigint): Promise<Enrollment>;
    getAdminCourses(): Promise<Array<Course>>;
    getAllEnrollments(): Promise<Array<Enrollment>>;
    getAllStudents(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourseById(id: bigint): Promise<Course | null>;
    getCourseCurriculum(courseId: bigint): Promise<Array<[Section, Array<Lesson>]>>;
    getCourseProgress(courseId: bigint): Promise<{
        totalLessons: bigint;
        completedLessons: bigint;
        percentage: bigint;
    }>;
    getCourses(): Promise<Array<Course>>;
    getMyEnrollments(): Promise<Array<Enrollment>>;
    getMyProgress(): Promise<Array<{
        courseId: bigint;
        percentage: bigint;
    }>>;
    getStats(): Promise<{
        totalEnrollments: bigint;
        totalStudents: bigint;
        totalCourses: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isEnrolled(courseId: bigint): Promise<boolean>;
    markLessonComplete(lessonId: bigint, courseId: bigint): Promise<LessonProgress>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCourse(id: bigint, title: string, description: string, category: string, price: bigint, thumbnailUrl: string, isPublished: boolean): Promise<Course>;
    updateLesson(id: bigint, title: string, videoUrl: string, duration: bigint, order: bigint): Promise<Lesson>;
    updateSection(id: bigint, title: string, order: bigint): Promise<Section>;
}
import type { Course as _Course, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLesson(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.addLesson(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLesson(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addSection(arg0: bigint, arg1: string, arg2: bigint): Promise<Section> {
        if (this.processError) {
            try {
                const result = await this.actor.addSection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSection(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteCourse(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteSection(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSection(arg0);
            return result;
        }
    }
    async enrollCourse(arg0: bigint): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollCourse(arg0);
            return result;
        }
    }
    async getAdminCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminCourses();
            return result;
        }
    }
    async getAllEnrollments(): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnrollments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnrollments();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseById(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseCurriculum(arg0: bigint): Promise<Array<[Section, Array<Lesson>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseCurriculum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseCurriculum(arg0);
            return result;
        }
    }
    async getCourseProgress(arg0: bigint): Promise<{
        totalLessons: bigint;
        completedLessons: bigint;
        percentage: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseProgress(arg0);
            return result;
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return result;
        }
    }
    async getMyEnrollments(): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollments();
            return result;
        }
    }
    async getMyProgress(): Promise<Array<{
        courseId: bigint;
        percentage: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return result;
        }
    }
    async getStats(): Promise<{
        totalEnrollments: bigint;
        totalStudents: bigint;
        totalCourses: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEnrolled(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEnrolled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEnrolled(arg0);
            return result;
        }
    }
    async markLessonComplete(arg0: bigint, arg1: bigint): Promise<LessonProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCourse(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: boolean): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateLesson(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSection(arg0: bigint, arg1: string, arg2: bigint): Promise<Section> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSection(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
